name: plant_py38_full
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.8.16
  - readline=8.2
  - sqlite=3.40.1
  - tk=8.6.12
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.6.2
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asciitree==0.3.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - azure-core==1.26.3
      - azure-storage-blob==12.15.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bleach==6.0.0
      - cachetools==5.3.0
      - cffi==1.15.1
      - cftime==1.6.2
      - charset-normalizer==3.0.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - comm==0.1.2
      - contourpy==1.0.7
      - cryptography==39.0.1
      - cycler==0.11.0
      - cython==0.29.33
      - dask==2023.2.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distinctipy==1.2.2
      - entrypoints==0.4
      - executing==1.2.0
      - exifread==3.0.0
      - fasteners==0.18
      - fastjsonschema==2.16.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.3
      - idna==3.4
      - imageio==2.25.1
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - intake==0.6.7
      - intake-xarray==0.6.1
      - ipyannotate==0.1.0b0
      - ipykernel==6.21.2
      - ipython==8.10.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isodate==0.6.1
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.0.3
      - jupyter-console==6.6.1
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-server==2.3.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - locket==1.0.0
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - msgpack==1.0.4
      - multidict==6.0.4
      - nbclassic==0.5.2
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - netcdf4==1.6.2
      - networkx==3.0
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numcodecs==0.11.0
      - numpy==1.24.2
      - oauthlib==3.2.2
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parhugin==0.0.3
      - parso==0.8.3
      - partd==1.3.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.0.0
      - pluggy==1.0.0
      - proj==0.2.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.37
      - protobuf==4.22.0
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pydantic==1.10.5
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyproj==3.4.1
      - pyrsistent==0.19.3
      - pytest==6.2.5
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - scikit-image==0.18.3
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - send2trash==1.8.0
      - setuptools==67.4.0
      - shapely==1.8.5.post1
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.2.3
      - timm==0.5.4
      - tinycss2==1.2.1
      - toml==0.10.2
      - toolz==0.12.0
      - torch==1.11.0
      - torchvision==0.12.0
      - tornado==6.2
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - uri-template==1.2.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.2.3
      - wheel==0.38.4
      - widgetsnbextension==4.0.5
      - xarray==2023.1.0
      - yarl==1.8.2
      - zarr==2.14.1
      - zipp==3.14.0
      - git+https://github.com/Living-with-machines/MapReader.git@b1be3afab8da7821bf1a0332acd4872e16bca570
      - scivision==0.7.0
